# Generated by Django 4.2.14 on 2024-09-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("model", models.CharField(max_length=128)),
                ("speed", models.IntegerField()),
                ("fuel", models.IntegerField()),
            ],
        ),
    ]
