# Generated by Django 4.2.14 on 2024-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("make", "model"), name="cars_car_unique_make_model"
            ),
        ),
    ]
